### PR TITLE
Feature/multisite redirects

### PR DESCRIPTION
**Pull request by BhanuKorthiwada**
Site properties require `redirectNode` to be configured for using the site-level redirect

### CODE REVIEW

**Comment by thecadams** [comment]
Thanks for the PR, hoping to test it very soon, and in the meantime @Chris-Castle would you be able to take a look at this too?

**Comment by thecadams** [comment]
Hi and thanks for the contribution! Unfortunately due to Sitecore and Microsoft ecosystem being unfriendly to casual users, I haven't been able to get an environment up and running to validate the PR. Can you please get a code-review from someone in another GitHub organization? If you can, I'll be happy to merge.

Cheers!
Chris

**Comment by BhanuKorthiwada** [comment]
no worries, Thank you!

**Comment by thecadams** [comment]
Heya! Thanks for the update! Happy to merge once you organize that code review.

**Comment by thecadams** [comment]
Hi! Any update on getting the review?

**Comment by thecadams** [comment]
Hi @BhanuKorthiwada looks like there are some merge conflicts, would you like to take a look and see if you can get it into a mergeable state, then get a code review? Thanks!

**Pull request closed without merging**
