### PR TITLE
Issue #49 : Dashes in source item breaking redirect

### PR DESCRIPTION
**Pull request by Mohamed-Syam**
https://github.com/thecadams/301RedirectModule/issues/49

### CODE REVIEW

**Comment by thecadams** [comment]
Looks good. Can I ask that you update the changelog and credit yourself in the README, as well? Your call on whether this is a minor or patch release.

**Comment by Mohamed-Syam** [comment]
Hey @thecadams,  I updated the read me file, thanks!

**Comment by thecadams** [comment]
Thanks - would you be willing to organize it so it's a patch release for those who track just the realeases?

**Comment by thecadams** [comment]
Actually on second thoughts I can take care of it. Thank you a ton for your contribution!

**Pull request merged**
