### PR TITLE
Fix performance issues by changing from SelectSingleItem to GetItem

### PR DESCRIPTION
**Pull request by markgibbons25**
Fix performance issues by changing from SelectSingleItem to GetItem so that it is cached and doesn't hit the DB every time.

Also remove fast query which is a known performance issue waiting to happen and deprecated feature.

### CODE REVIEW

**Comment by thecadams** [comment]
Hi, thanks for the PR! I’m not familiar with Sitecore these days but very happy to merge based on the way it looks.

Any concerns to be aware of for other users of the code with this PR in it?

**Comment by markgibbons25** [comment]
Thanks @thecadams , no concerns that I'm aware of, it should be backwards compatible to all supported versions. I've tested on Sitecore 10.3.

**Comment by thecadams** [comment]
Thanks. Going to merge on the back of what you’re saying!

Incidentally I’ve been unable to maintain this module lately and am looking for a new maintainer. If you’re interested, let’s chat!

**Comment by cadamsdotcom** [comment]
Congrats on becoming one of our contributors by the way. Going to have to add your name to the credits! 😃

**Comment by steviemcg** [comment]
Bit late to comment after the merge, but had some feedback. 

Users choosing fast will now fallback to .GetItem and probably crash. I'd fallback to query and add something to the logs.

SelectSingleItem supported query syntax and the new code doesn't. Why not check whether it's a query and decide which method to use accordingly. 

The performance benefits in this PR are obvious but they're less backwards compatible than I'd hope for in a public library.

**Comment by cadamsdotcom** [comment]
Hey there @steviemcg sounds like I merged a little too quick, but it’s all good, what if we reinstate the fast path?

**Pull request merged**
